# Generated by Django 4.1.5 on 2023-03-27 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TbMeranti',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cl_invest_name', models.CharField(max_length=100)),
                ('cl_current_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('cl_precentage_stonk', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
    ]
