# Generated by Django 4.1.5 on 2023-04-06 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homecontent', '0002_tbfam'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbfam',
            name='cl_invest_dest',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='tbmeranti',
            name='cl_invest_desc',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
