# Generated by Django 4.1.5 on 2023-04-06 07:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homecontent', '0003_tbfam_cl_invest_dest_tbmeranti_cl_invest_desc'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tbfam',
            old_name='cl_invest_dest',
            new_name='cl_invest_desc',
        ),
    ]
